#!/bin/bash

build() {
    local rules tool

    if [ -e /usr/lib/systemd/systemd-udevd ] ; then
        add_binary /usr/lib/systemd/systemd-udevd
    else
        add_binary /usr/lib64/systemd/systemd-udevd
    fi

    if [ -e /usr/bin/udevadm ]; then
        add_binary /usr/bin/udevadm
        add_binary /usr/bin/systemd-tmpfiles
    else
        add_binary /usr/sbin/udevadm
        add_binary /usr/sbin/systemd-tmpfiles
    fi

    for rules in 50-udev-default.rules 60-persistent-storage.rules 64-btrfs.rules 80-drivers.rules; do
        add_file "/usr/lib/udev/rules.d/$rules"
    done
    for tool in ata_id scsi_id; do
        add_file "/usr/lib/udev/$tool"
    done

    add_runscript
}

help() {
    cat <<HELPEOF
This hook adds the udev daemon to the initramfs, allowing for dynamic loading
of modules and reliable detection of the root device via tags (e.g. UUID or
LABEL). Do not remove this hook unless you are using the systemd hook, or you
know what you're doing.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
