#! /bin/bash

cd /usr/games/troubledwater

if [[ -x skwx_unx_x64 ]] ; then
	exec ./skwx_unx_x64
elif [[ -x skwx_unx ]] ; then
	exec ./skwx_unx
fi

echo "something bad happened! please re-emerge the game"

exit 1;
