#!/bin/sh

create_wine_dir ()
{
    # get params
    winedir=${1:?} ; shift			# only accept absolute path without trailing slash

    # exec wine command
    if [ ! -e "$winedir" ] ; then
        mkdir -p "$winedir"
    fi
    WINEPREFIX="$winedir" wineboot

    # change softlink to real directory in user directory
    userdir="$winedir/drive_c/users/$(id -un)"
    SAVEIFS=$IFS
    IFS=$'\n'
    for f in `find "$userdir" -print`
    do
        if [ ! -L "$f" ] ; then continue ; fi

        unlink $f
        mkdir $f
    done
}

create_link ()
{
    # get params
    srcdir=${1:?} ; shift			# only accept absolute path without trailing slash
    dstdir=${1:?} ; shift			# same as above
    dstdir_in="$dstdir/$(basename $srcdir)"
    
    # make dstdir in srcdir
    if [ ! -e "$dstdir_in" ] ; then
        mkdir -p "$dstdir_in"
    fi

    # do the job
    SAVEIFS=$IFS
    IFS=$'\n'
    for srcf in `find "$srcdir" -print`
    do
        # get inner filename
        f=${srcf:((${#srcdir}+1))}
        if [ "$f" == "" ] ; then continue ; fi

        # do the job
        if [[ -d "$srcf" && ! -L "$srcf" ]] ; then
            # create directory structure
            mkdir -p "$dstdir_in/$f"
        else
            # create softlink
            ln -s -t `dirname "$dstdir_in/$f"` $srcf
        fi
    done
    IFS=$SAVEIFS
}

get_cur_lang ()
{
    if [ ${LC_ALL:-x} != "x" ] ; then echo "$LC_ALL"
    elif [ ${LANG:-x} != "x" ] ; then echo "$LANG"
    elif [ ${LC_LANG:-x} != "x" ] ; then echo "$LC_LANG"
    else echo ""
    fi

    return 0
}

# Variables
GAMEDIR=		# fill by ebuild
DATADIR=		# fill by ebuild

# Create wine directory
create_wine_dir "$DATADIR"
WINEPREFIX="$DATADIR" winetricks d3dx9_43
WINEPREFIX="$DATADIR" winetricks d3dcompiler_43

# Make links of "$GAMEDIR/*" to "$DATADIR"
if [ ! -e "$DATADIR/drive_c/Limbo" ] ; then
    create_link "$GAMEDIR/Limbo" "$DATADIR/drive_c"

    # Copy default config file
    cp "$GAMEDIR/default-config/settings.txt" "$DATADIR/drive_c/Limbo/"
    chmod 664 "$DATADIR/drive_c/Limbo/settings.txt"
fi

# Change language setting
langu=$(get_cur_lang)
langu=${langu%%.*}
case "$langu" in
    fr)                         dstlang="fr" ;;
    zh_CN|zh_HK|zh_TW)          dstlang="zh" ;;
    pt|pt_BR|pt_PT)             dstlang="pt" ;;
    de)                         dstlang="de" ;;
    ko)                         dstlang="ko" ;;
    it)                         dstlang="it" ;;
    es|es_AR|es_CL|es_ES|es_MX) dstlang="es" ;;
    ja)                         dstlang="ja" ;;
    *)                          dstlang="uk" ;;
esac
cp "$DATADIR/drive_c/Limbo/settings.txt" "$DATADIR/drive_c/Limbo/settings.txt.last"
sed -e "s/^language.*$/language = \"$dstlang\"/g" "$DATADIR/drive_c/Limbo/settings.txt.last" > "$DATADIR/drive_c/Limbo/settings.txt"
rm -f "$DATADIR/drive_c/Limbo/settings.txt.last"

# run the game
cd "$DATADIR/drive_c/Limbo"
WINEPREFIX="$DATADIR" wine limbo.exe

