# Copyright 1999-2009 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $
# Ebuild generated by g-pypi 0.2.1 (rev. 204)

EAPI="3"
inherit distutils

DESCRIPTION="Platform-independent file locking module"
HOMEPAGE="http://smontanaro.dyndns.org/python/"
SRC_URI="http://smontanaro.dyndns.org/python/${P}.tar.gz"
LICENSE="MIT"
KEYWORDS="~x86"
SLOT="0"
RESTRICT="mirror"
IUSE=""

