#! /bin/bash

# for Qt applications, reset pixel ratio to 2.
export QT_AUTO_SCREEN_SCALE_FACTOR=2

# and force scale factor to 2.
export NETEASE_ARGS='--force-device-scale-factor=2'

export LD_LIBRARY_PATH=/usr/lib64/netease-cloud-music/lib

export QT_PLUGIN_PATH=/usr/lib64/netease-cloud-music/plugins

exec /usr/lib64/netease-cloud-music/lib/netease-cloud-music
