# Copyright 1999-2008 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header$

#       their indexes seem to be in a different format. So we'll keep them
#       seperate for now.

DESCRIPTION="Stardict dictionary pack for powerword v2007"
HOMEPAGE="http://stardict.sourceforge.net/"

LICENSE="GPL-2"
SLOT="0"
# when adding keywords, remember to add to stardict.eclass
KEYWORDS="~sparc ~x86 ~amd64"

DEP="app-text/stardict-powerword_pw7ecdiz
app-text/stardict-powerword_pw7ecdl
app-text/stardict-powerword_pw7ecdz
app-text/stardict-powerword_pw7ecdzg
app-text/stardict-powerword_pw7ecgg
app-text/stardict-powerword_pw7echx
app-text/stardict-powerword_pw7ecjx
app-text/stardict-powerword_pw7ecjxg
app-text/stardict-powerword_pw7ecjz
app-text/stardict-powerword_pw7ecky
app-text/stardict-powerword_pw7ecny
app-text/stardict-powerword_pw7ecqgy
app-text/stardict-powerword_pw7ecsw
app-text/stardict-powerword_pw7ecsx
app-text/stardict-powerword_pw7ecwl
app-text/stardict-powerword_pw7ecxx
app-text/stardict-powerword_pw7ecyj
app-text/stardict-powerword_pw7ecyx
app-text/stardict-powerword_pw7ecyzn
app-text/stardict-powerword_pwdccac
app-text/stardict-powerword_pwdcccjk
app-text/stardict-powerword_pwdecahd
app-text/stardict-powerword_pwdecmc
app-text/stardict-powerword_pwdecmec
app-text/stardict-powerword_pwdectj
app-text/stardict-powerword_pwdecyf
app-text/stardict-powerword_pwdeeahd
app-text/stardict-powerword_pwdnnjsj
app-text/stardict-powerword_pwdnnsz
app-text/stardict-powerword_pwdnnxc
app-text/stardict-powerword_pwdsyhr
app-text/stardict-powerword_pwdxrh
app-text/stardict-powerword_pwgcecb
app-text/stardict-powerword_pwgcech
app-text/stardict-powerword_pwgcedg
app-text/stardict-powerword_pwgcedl
app-text/stardict-powerword_pwgcedq
app-text/stardict-powerword_pwgcedqw
app-text/stardict-powerword_pwgcedw
app-text/stardict-powerword_pwgcedz
app-text/stardict-powerword_pwgcedzh
app-text/stardict-powerword_pwgcegl
app-text/stardict-powerword_pwgcegsw
app-text/stardict-powerword_pwgcehg
app-text/stardict-powerword_pwgcehh
app-text/stardict-powerword_pwgcehx
app-text/stardict-powerword_pwgcehy
app-text/stardict-powerword_pwgcejix
app-text/stardict-powerword_pwgcejpx
app-text/stardict-powerword_pwgcejs2
app-text/stardict-powerword_pwgcejz
app-text/stardict-powerword_pwgcekc
app-text/stardict-powerword_pwgcelix
app-text/stardict-powerword_pwgcelx
app-text/stardict-powerword_pwgcemt
app-text/stardict-powerword_pwgcenx
app-text/stardict-powerword_pwgcept
app-text/stardict-powerword_pwgceshh
app-text/stardict-powerword_pwgceshl
app-text/stardict-powerword_pwgcesl
app-text/stardict-powerword_pwgcesww
app-text/stardict-powerword_pwgcesx
app-text/stardict-powerword_pwgcesy
app-text/stardict-powerword_pwgcetd
app-text/stardict-powerword_pwgcetr
app-text/stardict-powerword_pwgcetw
app-text/stardict-powerword_pwgcewl
app-text/stardict-powerword_pwgcewsw
app-text/stardict-powerword_pwgcexb
app-text/stardict-powerword_pwgcexli
app-text/stardict-powerword_pwgceyao
app-text/stardict-powerword_pwgceych
app-text/stardict-powerword_pwgceyj
app-text/stardict-powerword_pwgceyx1
app-text/stardict-powerword_pwgceyx2
app-text/stardict-powerword_pwgceyx3
app-text/stardict-powerword_pwgceyx4
app-text/stardict-powerword_pwgceyx5
app-text/stardict-powerword_pwgceyx6
app-text/stardict-powerword_pwgceyx7
app-text/stardict-powerword_pwgcezdh
app-text/stardict-powerword_pwgcezhw
app-text/stardict-powerword_pwgcezzh
app-text/stardict-powerword_pwgeccb
app-text/stardict-powerword_pwgecch
app-text/stardict-powerword_pwgecdg
app-text/stardict-powerword_pwgecdl
app-text/stardict-powerword_pwgecdq
app-text/stardict-powerword_pwgecdqw
app-text/stardict-powerword_pwgecdw
app-text/stardict-powerword_pwgecdz
app-text/stardict-powerword_pwgecdzh
app-text/stardict-powerword_pwgecgl
app-text/stardict-powerword_pwgecgsw
app-text/stardict-powerword_pwgechg
app-text/stardict-powerword_pwgechh
app-text/stardict-powerword_pwgechx
app-text/stardict-powerword_pwgechy
app-text/stardict-powerword_pwgecjix
app-text/stardict-powerword_pwgecjpx
app-text/stardict-powerword_pwgecjs2
app-text/stardict-powerword_pwgecjz
app-text/stardict-powerword_pwgeckc
app-text/stardict-powerword_pwgeclix
app-text/stardict-powerword_pwgeclx
app-text/stardict-powerword_pwgecmt
app-text/stardict-powerword_pwgecnx
app-text/stardict-powerword_pwgecpt
app-text/stardict-powerword_pwgecshh
app-text/stardict-powerword_pwgecshl
app-text/stardict-powerword_pwgecsl
app-text/stardict-powerword_pwgecsww
app-text/stardict-powerword_pwgecsx
app-text/stardict-powerword_pwgecsy
app-text/stardict-powerword_pwgectd
app-text/stardict-powerword_pwgectr
app-text/stardict-powerword_pwgectw
app-text/stardict-powerword_pwgecwl
app-text/stardict-powerword_pwgecwsw
app-text/stardict-powerword_pwgecxb
app-text/stardict-powerword_pwgecxli
app-text/stardict-powerword_pwgecyao
app-text/stardict-powerword_pwgecych
app-text/stardict-powerword_pwgecyj
app-text/stardict-powerword_pwgecyx1
app-text/stardict-powerword_pwgecyx2
app-text/stardict-powerword_pwgecyx3
app-text/stardict-powerword_pwgecyx4
app-text/stardict-powerword_pwgecyx5
app-text/stardict-powerword_pwgecyx6
app-text/stardict-powerword_pwgecyx7
app-text/stardict-powerword_pwgeczdh
app-text/stardict-powerword_pwgeczhw
app-text/stardict-powerword_pwgeczzh
app-text/stardict-powerword_pwpcefl
app-text/stardict-powerword_pwpcehh
app-text/stardict-powerword_pwpcejck
app-text/stardict-powerword_pwpcejm
app-text/stardict-powerword_pwpcekj
app-text/stardict-powerword_pwpcexf
app-text/stardict-powerword_pwpcexw
app-text/stardict-powerword_pwpecdn
app-text/stardict-powerword_pwpechh
app-text/stardict-powerword_pwpechx
app-text/stardict-powerword_pwpecjck
app-text/stardict-powerword_pwpecjm
app-text/stardict-powerword_pwpeckj
app-text/stardict-powerword_pwpecqhk
app-text/stardict-powerword_pwpecxf
app-text/stardict-powerword_pwpecxlx
app-text/stardict-powerword_pwpecxw
app-text/stardict-powerword_pwpecyq
app-text/stardict-powerword_pwqce
app-text/stardict-powerword_pwqdsyhr
app-text/stardict-powerword_pwqdxrh
app-text/stardict-powerword_pwqec
app-text/stardict-powerword_pwrcc
app-text/stardict-powerword_pwree
app-text/stardict-powerword_pwzcezl
app-text/stardict-powerword_pwzeczl"
DEPEND="${DEP}"
