# Copyright 2024-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Autogenerated by pycargoebuild 0.13.2

EAPI=8

CRATES="
"

RUST_MIN_VER="1.88.0"

inherit cargo shell-completion

DESCRIPTION="A command-line application for interacting with git repositories"
HOMEPAGE="https://github.com/GitoxideLabs/gitoxide"
SRC_URI="
	https://github.com/GitoxideLabs/gitoxide/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	https://github.com/gentoo-zh-drafts/${PN}/releases/download/v${PV}/${P}-crates.tar.xz
	${CARGO_CRATE_URIS}
"

LICENSE="|| ( Apache-2.0 MIT )"
# Dependent crate licenses
LICENSE+="
	Apache-2.0 BSD CDLA-Permissive-2.0 ISC MIT MPL-2.0 openssl
	Unicode-3.0 ZLIB
"
SLOT="0"
KEYWORDS="~amd64"

src_compile() {
	cargo_src_compile

	mkdir -pv completions || die
	for bin in gix ein; do
		./$(cargo_target_dir)/${bin} completions -s bash > completions/${bin} || die
		./$(cargo_target_dir)/${bin} completions -s zsh > completions/_${bin} || die
		./$(cargo_target_dir)/${bin} completions -s fish > completions/${bin}.fish || die
	done
}

src_install(){
	for bin in gix ein; do
		dobin "$(cargo_target_dir)/${bin}"
		dobashcomp completions/${bin}
		dofishcomp completions/${bin}.fish
		dozshcomp completions/_${bin}
	done
}
