#! /bin/bash
# gcin-filter-nobopomofo version 0.0.4
  read -r -t 1 aa
  echo -n $aa
  if [ "$(echo -n $aa | grep -v -f $0 --)" = "" ]; then
    declare -i bb=$(date +%N | tr -d 0)%2
    if [ "$bb" = "1" ]; then
      gcin-message -icon /usr/share/pixmaps/gcin/SS1135_ST.jpg -duration 1500 &
    else
      gcin-message -icon /usr/share/pixmaps/gcin/SS1208_DT.jpg -duration 1500 &
    fi
  fi
  exit
ㄅ
ㄆ
ㄇ
ㄈ
ㄉ
ㄊ
ㄋ
ㄌ
ㄍ
ㄎ
ㄏ
ㄐ
ㄑ
ㄒ
ㄓ
ㄔ
ㄕ
ㄖ
ㄗ
ㄘ
ㄙ
ㄧ
ㄨ
ㄩ
ㄚ
ㄛ
ㄜ
ㄝ
ㄞ
ㄟ
ㄠ
ㄡ
ㄢ
ㄣ
ㄤ
ㄥ
ㄦ
