name: pkgcheck
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request_target:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - 'metadata/**'
      - 'profiles/**'
      - 'README.md'
      - '.gitignore'
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Run pkgcheck
      uses: pkgcore/pkgcheck-action@v1
