name: Sync with upstream

on:
  push:
    branches: [ master ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Fetch upstream changes
        run: git fetch git fetch https://github.com/microcai/gentoo-zh.git upstream

      - name: Merge upstream changes
        run: git merge upstream/master

      - name: Push changes to origin
        run: git push origin master
